name: Build and Push to ECR

on:
  push:
    branches:
      - deployment_version

env:
  AWS_REGION: eu-west-3         
  # Noms des repositories ECR
  ECR_REPO_ML: g2-mg02-news-reco-ml
  ECR_REPO_API: g2-mg02-news-reco-api
  ECR_REPO_FRONTEND: g2-mg02-news-reco-frontend

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Récupération du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installation de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # tests unitaires
      - name: Run Unit Tests
        env:
          PYTHONPATH: .
          #  dummy variables pour passer la validation au démarrage
          SUPABASE_URL: "https://test.supabase.co"
          SUPABASE_KEY: "dummy-key-for-tests"
        run: |
          echo "Installation des dépendances de test..."
          pip install pytest httpx
          
          pip install fastapi uvicorn "pydantic[email]" supabase
          
          echo "Running API Tests..."
          python -m pytest api/tests/
          
          echo "Running ML API Tests..."
          
          python -m pytest ml/tests/

      # Téléchargement des fichiers du modèle
      - name: Download ML Models
        run: |
          python download-models.py
          ls -R ml/models/

      # Connexion à AWS 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build & Push - Service ML
      - name: Build and push ML image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO_ML:latest -f ml/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPO_ML:latest

      # Build & Push - Service API pour supabase
      - name: Build and push API image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO_API:latest -f api/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPO_API:latest

      # Build & Push - Service Frontend
      - name: Build and push Frontend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO_FRONTEND:latest -f frontend/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPO_FRONTEND:latest

      # Déploiement sur ECS (Force Update)
      - name: Force ECS Deployment
        run: |
          aws ecs update-service --cluster g2-mg02-news-reco-cluster --service g2-mg02-news-reco-task-service-nyvdt5tq --force-new-deployment --region eu-west-3