name: Model Training Pipeline (EC2)

on:
  workflow_dispatch:

jobs:
  # JOB 1 : Entraînement
  train-model:
    name: 1. Train Model (EC2)
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip3 install -r ml/model_requirements.txt
          pip3 install gdown

      - name: Run Training Script
        run: |
          python3 ml/train_model.py
      
      # Sauvegarde des résultats pour le job suivant
      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-artifacts
          path: artifacts/
          retention-days: 1

  # JOB 2 : Upload S3
  upload-s3:
    name: 2. Upload to S3
    runs-on: self-hosted
    needs: train-model  # Attend que le job 1 soit fini
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Récupération des résultats du job 1
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: trained-model-artifacts
          path: artifacts/

      - name: Install Upload Dependencies
        run: pip3 install boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Upload Script
        run: |
          python3 ml/upload_model.py